### ISSUE TITLE
推荐项目Jvppeteer

### ISSUE THREAD

**Issue by fanyong920** [rockswang/awesome-java-crawler#3]
[项目地址：](https://github.com/fanyong920/jvppeteer)
项目介绍：Jvppeteer通过DevTools控制 Chromium 或 Chrome。 默认情况下，以headless模式运行，也可以通过配置运行'有头'模式。是Puppeteer的java的实现版本，实现了puppeteer的所有功能。

**Comment by rockswang** [comment]
已添加，请加油！
